version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: microservicesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgresuser:postgrespassword@db:5432/microservicesdb"
      NODE_ENV: development
      PORT: 3002

volumes:
  postgres-data:
